cat("\n Reading external parameters ...")
logfile$parameters$external<-list()
logfile$parameters$external$EICor_delRT<-5
logfile$parameters$external$EICor_minpeaks<-10
logfile$parameters$external$EICor_mincor<-.95
logfile$parameters$external$isotop_mztol<-2.5
logfile$parameters$external$isotop_ppm<-TRUE
logfile$parameters$external$isotop_inttol<-0.5
logfile$parameters$external$isotop_rttol<-5
logfile$parameters$external$isotop_use_charges<-c(1,2)
logfile$parameters$external$adducts_rttol<-5
logfile$parameters$external$adducts_mztol<-2.5
logfile$parameters$external$adducts_ppm<-TRUE
logfile$parameters$external$adducts_pos<-c("M+H","M+Na","M+K","M+NH4")
logfile$parameters$external$adducts_neg<-c("M-H","M-","2M-H")
logfile$parameters$external$homol_units<-c("CH2","CH4O")
logfile$parameters$external$homol_charges<-c(1,2)
logfile$parameters$external$homol_minmz<-10
logfile$parameters$external$homol_maxmz<-120
logfile$parameters$external$homol_minrt<-10
logfile$parameters$external$homol_maxrt<-60
logfile$parameters$external$homol_ppm<-TRUE
logfile$parameters$external$homol_mztol<-2.5
logfile$parameters$external$homol_rttol<-20
logfile$parameters$external$homol_minlength<-6
logfile$parameters$external$homol_vec_size<-1E8
cat("done.")
