MQMLW5964K <- function(
profileList,
n_global=10,
n_present=10,
use_present=FALSE,
highlight=FALSE
){
getit<-seq(1,length(profileList[[7]][,1]),1)
getit_global<-getit[profileList[[7]][,6]!=0]
getit_global<-getit_global[order(profileList[[7]][getit_global,6],decreasing=TRUE)]
getit_global<-getit_global[1:n_global]
if(use_present=="FALSE"){
getit_present<-getit[profileList[[7]][,5]!=0]
getit_present<-getit_present[order(profileList[[7]][getit_present,5],decreasing=TRUE)]
getit_present<-getit_present[1:n_present]
}else{
getit_present<-use_present
}
VKEWR9489N(
profileList,
getit_global[1],
logint=FALSE,
blindsub=FALSE,
blindfold=100,
lags=c(5,14),
threshold=3,
add=FALSE,
textit=FALSE,
simple=TRUE,
colorit="darkgrey",
use_lwd=1
)
if(n_global>1){
for(i in 2:n_global){
VKEWR9489N(
profileList,
getit_global[i],
logint=FALSE,
blindsub=FALSE,
blindfold=100,
lags=c(5,14),
threshold=3,
add=TRUE,
textit=FALSE,
simple=TRUE,
colorit="darkgrey",
use_lwd=1
)
}
}
if(highlight[1]!=FALSE){
for(i in 1:length(highlight)){
VKEWR9489N(
profileList,
highlight[i],
logint=FALSE,
blindsub=FALSE,
blindfold=100,
lags=c(5,14),
threshold=3,
add=TRUE,
textit=FALSE,
simple=TRUE,
colorit="red",
use_lwd=2
)
}
}
if(highlight[1]==FALSE){
for(i in 1:n_present){
VKEWR9489N(
profileList,
getit_present[i],
logint=FALSE,
blindsub=FALSE,
blindfold=100,
lags=c(5,14),
threshold=3,
add=TRUE,
textit=FALSE,
simple=TRUE,
colorit="red",
use_lwd=1
)
}
}
}
