# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
getEIC_new <- function(mz, RT, intens, orderedint, orderedret, dmzdens, ppm2, drtdens, merged2) {
    .Call('_enviMass_getEIC_new', PACKAGE = 'enviMass', mz, RT, intens, orderedint, orderedret, dmzdens, ppm2, drtdens, merged2)
}
series_relat <- function(homol_peaks_relat, range_mz, range_RT) {
    .Call('_enviMass_series_relat', PACKAGE = 'enviMass', homol_peaks_relat, range_mz, range_RT)
}
moving_count <- function(homol_peaks_relat, deldel) {
    .Call('_enviMass_moving_count', PACKAGE = 'enviMass', homol_peaks_relat, deldel)
}
compare <- function(a, b, results) {
    .Call('_enviMass_compare', PACKAGE = 'enviMass', a, b, results)
}
correct_intens <- function(corfac, sampleID, intens, sampleID_peak) {
    .Call('_enviMass_correct_intens', PACKAGE = 'enviMass', corfac, sampleID, intens, sampleID_peak)
}
metagroup <- function(proffrom, profto) {
    .Call('_enviMass_metagroup', PACKAGE = 'enviMass', proffrom, profto)
}
profpeakprof <- function(ProPeak_pro, ProPeak_peak, Peak_peak1, Peak_peak2, Peak_score, PeakPro) {
    .Call('_enviMass_profpeakprof', PACKAGE = 'enviMass', ProPeak_pro, ProPeak_peak, Peak_peak1, Peak_peak2, Peak_score, PeakPro)
}
mergeProfiles <- function(mz_lower, mz_upper, RT_lower, RT_upper, intens, sam, orderedint, orderedsam, supress) {
    .Call('_enviMass_mergeProfiles', PACKAGE = 'enviMass', mz_lower, mz_upper, RT_lower, RT_upper, intens, sam, orderedint, orderedsam, supress)
}
neighbour <- function(mz, rt, sample, maxsample, ppm, dmz, drt) {
    .Call('_enviMass_neighbour', PACKAGE = 'enviMass', mz, rt, sample, maxsample, ppm, dmz, drt)
}
agglom <- function(mz, rt, sample, ppm, dmz, drt) {
    .Call('_enviMass_agglom', PACKAGE = 'enviMass', mz, rt, sample, ppm, dmz, drt)
}
indexed <- function(index, maxindex, many) {
    .Call('_enviMass_indexed', PACKAGE = 'enviMass', index, maxindex, many)
}
fill_timeset <- function(timeset, sampleID, intensity, lengtimeset) {
    .Call('_enviMass_fill_timeset', PACKAGE = 'enviMass', timeset, sampleID, intensity, lengtimeset)
}
meandel <- function(timeset, subit, subrat, numtime, getwhat, lags, threshold, notrend) {
    .Call('_enviMass_meandel', PACKAGE = 'enviMass', timeset, subit, subrat, numtime, getwhat, lags, threshold, notrend)
}
intdiff <- function(timeset, subit, subrat, numtime, getwhat) {
    .Call('_enviMass_intdiff', PACKAGE = 'enviMass', timeset, subit, subrat, numtime, getwhat)
}
plot_prof <- function(RTlim_low, RTlim_up, mzlim_low, mzlim_up, mz, RT, intensity, sampleID, color1, color2, whatcolor) {
    .Call('_enviMass_plot_prof', PACKAGE = 'enviMass', RTlim_low, RTlim_up, mzlim_low, mzlim_up, mz, RT, intensity, sampleID, color1, color2, whatcolor)
}
binRT_prof <- function(RT, intensity, binRT, colorit, what) {
    .Call('_enviMass_binRT_prof', PACKAGE = 'enviMass', RT, intensity, binRT, colorit, what)
}
binmz_prof <- function(mz, intensity, binmzs, colorit) {
    .Call('_enviMass_binmz_prof', PACKAGE = 'enviMass', mz, intensity, binmzs, colorit)
}
init_MSraw <- function(file_path, sep_dim, type) {
    .Call('_enviMass_init_MSraw', PACKAGE = 'enviMass', file_path, sep_dim, type)
}
MSraw_size <- function() {
    .Call('_enviMass_MSraw_size', PACKAGE = 'enviMass')
}
read_header_MSraw_num <- function(file_path) {
    .Call('_enviMass_read_header_MSraw_num', PACKAGE = 'enviMass', file_path)
}
write_checksum_MSraw <- function(file_path, checksum) {
    .Call('_enviMass_write_checksum_MSraw', PACKAGE = 'enviMass', file_path, checksum)
}
read_checksum_MSraw <- function(file_path) {
    .Call('_enviMass_read_checksum_MSraw', PACKAGE = 'enviMass', file_path)
}
erase_checksum_MSraw <- function(file_path) {
    .Call('_enviMass_erase_checksum_MSraw', PACKAGE = 'enviMass', file_path)
}
write_centroids_MSraw <- function(file_path, scan_RTs, scan_IDs, centroids, match_scans_RT, skip_prof_index) {
    .Call('_enviMass_write_centroids_MSraw', PACKAGE = 'enviMass', file_path, scan_RTs, scan_IDs, centroids, match_scans_RT, skip_prof_index)
}
read_scanRTs_MSraw <- function(file_path) {
    .Call('_enviMass_read_scanRTs_MSraw', PACKAGE = 'enviMass', file_path)
}
read_scanIDs_MSraw <- function(file_path) {
    .Call('_enviMass_read_scanIDs_MSraw', PACKAGE = 'enviMass', file_path)
}
read_centroids_MSraw <- function(file_path, insert_RT, use_ID, read_all, get_index) {
    .Call('_enviMass_read_centroids_MSraw', PACKAGE = 'enviMass', file_path, insert_RT, use_ID, read_all, get_index)
}
read_scan_MSraw <- function(file_path, scan_ID, read_all) {
    .Call('_enviMass_read_scan_MSraw', PACKAGE = 'enviMass', file_path, scan_ID, read_all)
}
write_partition_MSraw <- function(file_path, partition_index) {
    .Call('_enviMass_write_partition_MSraw', PACKAGE = 'enviMass', file_path, partition_index)
}
read_partition_MSraw <- function(file_path, insert_RT, index_convert) {
    .Call('_enviMass_read_partition_MSraw', PACKAGE = 'enviMass', file_path, insert_RT, index_convert)
}
write_EIC_MSraw <- function(file_path, EIC_index) {
    .Call('_enviMass_write_EIC_MSraw', PACKAGE = 'enviMass', file_path, EIC_index)
}
read_EIC_MSraw <- function(file_path, index_convert) {
    .Call('_enviMass_read_EIC_MSraw', PACKAGE = 'enviMass', file_path, index_convert)
}
write_peaks_MSraw <- function(file_path, peak_index, peak_info) {
    .Call('_enviMass_write_peaks_MSraw', PACKAGE = 'enviMass', file_path, peak_index, peak_info)
}
read_peaks_MSraw <- function(file_path, index_convert) {
    .Call('_enviMass_read_peaks_MSraw', PACKAGE = 'enviMass', file_path, index_convert)
}
read_single_EIC_MSraw <- function(file_path, EIC_indices, insert_RT, use_ID) {
    .Call('_enviMass_read_single_EIC_MSraw', PACKAGE = 'enviMass', file_path, EIC_indices, insert_RT, use_ID)
}
filter_centroids_MSraw <- function(file_path, min_RT, max_RT, min_mass, max_mass, insert_RT, read_all, use_partitions, get_XIC) {
    .Call('_enviMass_filter_centroids_MSraw', PACKAGE = 'enviMass', file_path, min_RT, max_RT, min_mass, max_mass, insert_RT, read_all, use_partitions, get_XIC)
}
extractProfiles <- function(peaks, in_order, dmass, ppm, dret) {
    .Call('_enviMass_extractProfiles', PACKAGE = 'enviMass', peaks, in_order, dmass, ppm, dret)
}
extractProfiles_replicates <- function(peaks, in_order, dmass, ppm, dret, pregroup) {
    .Call('_enviMass_extractProfiles_replicates', PACKAGE = 'enviMass', peaks, in_order, dmass, ppm, dret, pregroup)
}
while_checked <- function(check_nodes, pattern_compound, peaks, RT_tol_inside, int_tol, verbose) {
    .Call('_enviMass_while_checked', PACKAGE = 'enviMass', check_nodes, pattern_compound, peaks, RT_tol_inside, int_tol, verbose)
}
