# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

getEIC_new <- function(mz, RT, intens, orderedint, orderedret, dmzdens, ppm2, drtdens, merged2) {
    .Call('_enviMass_getEIC_new', PACKAGE = 'enviMass', mz, RT, intens, orderedint, orderedret, dmzdens, ppm2, drtdens, merged2)
}

series_relat <- function(homol_peaks_relat, range_mz, range_RT) {
    .Call('_enviMass_series_relat', PACKAGE = 'enviMass', homol_peaks_relat, range_mz, range_RT)
}

moving_count <- function(homol_peaks_relat, deldel) {
    .Call('_enviMass_moving_count', PACKAGE = 'enviMass', homol_peaks_relat, deldel)
}

compare <- function(a, b, results) {
    .Call('_enviMass_compare', PACKAGE = 'enviMass', a, b, results)
}

correct_intens <- function(corfac, sampleID, intens, sampleID_peak) {
    .Call('_enviMass_correct_intens', PACKAGE = 'enviMass', corfac, sampleID, intens, sampleID_peak)
}

metagroup <- function(proffrom, profto) {
    .Call('_enviMass_metagroup', PACKAGE = 'enviMass', proffrom, profto)
}

profpeakprof <- function(ProPeak_pro, ProPeak_peak, Peak_peak1, Peak_peak2, Peak_score, PeakPro) {
    .Call('_enviMass_profpeakprof', PACKAGE = 'enviMass', ProPeak_pro, ProPeak_peak, Peak_peak1, Peak_peak2, Peak_score, PeakPro)
}

mergeProfiles <- function(mz_lower, mz_upper, RT_lower, RT_upper, intens, sam, orderedint, orderedsam, supress) {
    .Call('_enviMass_mergeProfiles', PACKAGE = 'enviMass', mz_lower, mz_upper, RT_lower, RT_upper, intens, sam, orderedint, orderedsam, supress)
}

neighbour <- function(mz, rt, sample, maxsample, ppm, dmz, drt) {
    .Call('_enviMass_neighbour', PACKAGE = 'enviMass', mz, rt, sample, maxsample, ppm, dmz, drt)
}

agglom <- function(mz, rt, sample, ppm, dmz, drt) {
    .Call('_enviMass_agglom', PACKAGE = 'enviMass', mz, rt, sample, ppm, dmz, drt)
}

indexed <- function(index, maxindex, many) {
    .Call('_enviMass_indexed', PACKAGE = 'enviMass', index, maxindex, many)
}

fill_timeset <- function(timeset, sampleID, intensity, lengtimeset) {
    .Call('_enviMass_fill_timeset', PACKAGE = 'enviMass', timeset, sampleID, intensity, lengtimeset)
}

meandel <- function(timeset, subit, subrat, numtime, getwhat, lags, threshold, notrend) {
    .Call('_enviMass_meandel', PACKAGE = 'enviMass', timeset, subit, subrat, numtime, getwhat, lags, threshold, notrend)
}

intdiff <- function(timeset, subit, subrat, numtime, getwhat) {
    .Call('_enviMass_intdiff', PACKAGE = 'enviMass', timeset, subit, subrat, numtime, getwhat)
}

plot_prof <- function(RTlim_low, RTlim_up, mzlim_low, mzlim_up, mz, RT, intensity, sampleID, color1, color2, whatcolor) {
    .Call('_enviMass_plot_prof', PACKAGE = 'enviMass', RTlim_low, RTlim_up, mzlim_low, mzlim_up, mz, RT, intensity, sampleID, color1, color2, whatcolor)
}

binRT_prof <- function(RT, intensity, binRT, colorit, what) {
    .Call('_enviMass_binRT_prof', PACKAGE = 'enviMass', RT, intensity, binRT, colorit, what)
}

binmz_prof <- function(mz, intensity, binmzs, colorit) {
    .Call('_enviMass_binmz_prof', PACKAGE = 'enviMass', mz, intensity, binmzs, colorit)
}

extractProfiles <- function(peaks, in_order, dmass, ppm, dret) {
    .Call('_enviMass_extractProfiles', PACKAGE = 'enviMass', peaks, in_order, dmass, ppm, dret)
}

extractProfiles_replicates <- function(peaks, in_order, dmass, ppm, dret, pregroup) {
    .Call('_enviMass_extractProfiles_replicates', PACKAGE = 'enviMass', peaks, in_order, dmass, ppm, dret, pregroup)
}

result_exists <- function(check_nodes_sub, results_peaks, at_size) {
    .Call('_enviMass_result_exists', PACKAGE = 'enviMass', check_nodes_sub, results_peaks, at_size)
}

while_checked <- function(check_nodes, pattern_compound, peaks, RT_tol_inside, int_tol) {
    .Call('_enviMass_while_checked', PACKAGE = 'enviMass', check_nodes, pattern_compound, peaks, RT_tol_inside, int_tol)
}

